/*
 * generated by Xtext
 */
package expr2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Expr2DslUiModule extends expr2.ui.AbstractExpr2DslUiModule {
	public Expr2DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
