/*
* generated by Xtext
*/
package expr2.ui.contentassist;

import expr2.ui.contentassist.AbstractExpr2DslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Expr2DslProposalProvider extends AbstractExpr2DslProposalProvider {

}
