/*
 * generated by Xtext
 */
package expr;

import de.itemis.xtext.typesystem.ITypesystem;
import expr.typesystem.ExprTypesystem;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExprDemoRuntimeModule extends expr.AbstractExprDemoRuntimeModule {

	public Class<? extends ITypesystem> bindITypestem() {
		return ExprTypesystem.class;
	}

	
}
