/*
 * generated by Xtext
 */
package de.itemis.xtext.typesystem.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TsDslRuntimeModule extends de.itemis.xtext.typesystem.dsl.AbstractTsDslRuntimeModule {

}
