/*
* generated by Xtext
*/
package de.itemis.xtext.typesystem.dsl.ui.contentassist;

import de.itemis.xtext.typesystem.dsl.ui.contentassist.AbstractTsDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TsDslProposalProvider extends AbstractTsDslProposalProvider {

}
