/*
 * generated by Xtext
 */
package de.itemis.xtext.typesystem.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;

import de.itemis.xtext.typesystem.dsl.ui.hyperlinking.MyHyperlinlHelper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TsDslUiModule extends
		de.itemis.xtext.typesystem.dsl.ui.AbstractTsDslUiModule {
	public TsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
		return MyHyperlinlHelper.class;
	}
}
