/*
* generated by Xtext
*/
package expr2.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class Expr2DslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
