/*
 * generated by Xtext
 */
package expr2;

import de.itemis.xtext.typesystem.ITypesystem;
import expr2.typesys.Expr2Typesystem;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Expr2DslRuntimeModule extends expr2.AbstractExpr2DslRuntimeModule {

	public Class<? extends ITypesystem> bindITypestem() {
		return Expr2Typesystem.class;   
	}

	
}
